"""Add profile_picture and bio to User model

Revision ID: 069c777775b3
Revises: b617a61ea360
Create Date: 2025-02-26 08:51:52.807171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069c777775b3'
down_revision = 'b617a61ea360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
