"""Add playdate_message table

Revision ID: 1a7ffd48d5de
Revises: ba81a080a113
Create Date: 2025-02-28 02:25:41.280239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7ffd48d5de'
down_revision = 'ba81a080a113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playdate_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playdate_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playdate_id'], ['playdate.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playdate_message')
    # ### end Alembic commands ###
