"""rename_profile_picture_to_image_filename

Revision ID: 503c294cbe23
Revises: cf1535a34b99
Create Date: 2025-03-04 11:04:56.732782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503c294cbe23'
down_revision = 'cf1535a34b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
