"""Add status and max_pets fields to Playdate model

Revision ID: 5f28dafee686
Revises: 1a7ffd48d5de
Create Date: 2025-03-03 01:24:04.394761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f28dafee686'
down_revision = '1a7ffd48d5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playdate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('max_pets', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playdate', schema=None) as batch_op:
        batch_op.drop_column('max_pets')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
