"""Add playdate_attendees table

Revision ID: ba81a080a113
Revises: 5fac648cdb98
Create Date: 2025-02-26 19:51:00.349386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba81a080a113'
down_revision = '5fac648cdb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playdate', schema=None) as batch_op:
        batch_op.drop_column('max_pets')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playdate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('max_pets', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
