"""Add admin fields to User model

Revision ID: fb43ed796de0
Revises: 503c294cbe23
Create Date: 2025-03-04 11:27:27.456043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb43ed796de0'
down_revision = '503c294cbe23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('account_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_notes')
        batch_op.drop_column('last_login')
        batch_op.drop_column('account_status')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
